// Approximate neighbourhood centres, not venue coordinates.
const TOKYO_GROUPS=[
 {id:'north',name:'Ikebukuro',sub:'Ikebukuro + Zoshigaya',lat:35.727,lng:139.713,areas:['Ikebukuro','Zoshigaya'],hint:'Northwest Tokyo. The biggest concentration of food places in your list.'},
 {id:'shinjuku',name:'Shinjuku',sub:'Shinjuku',lat:35.691,lng:139.701,areas:['Shinjuku'],hint:'West of central Tokyo, between Ikebukuro and Shibuya on the map.'},
 {id:'west',name:'Shibuya',sub:'Shibuya + Harajuku',lat:35.664,lng:139.702,areas:['Shibuya','Harajuku'],hint:'Southwest Tokyo. This cluster combines the sheet’s Shibuya and Harajuku places.'},
 {id:'central',name:'Ginza',sub:'Ginza + Tokyo Station',lat:35.675,lng:139.765,areas:['Ginza','Tokyo Station'],hint:'Central Tokyo, east of Shibuya and Shinjuku. Ginza and Tokyo Station are grouped here.'},
 {id:'roppongi',name:'Roppongi',sub:'Roppongi',lat:35.663,lng:139.732,areas:['Roppongi'],hint:'Between Shibuya and Ginza, south of the central city.'},
 {id:'east',name:'Akihabara',sub:'Akihabara',lat:35.699,lng:139.773,areas:['Akihabara'],hint:'Northeast of Ginza and Tokyo Station. Area assignment comes from the spreadsheet.'}
];
let selectedCluster=null;
const mapState={lat:35.697,lng:139.738,zoom:12,loaded:false,tiles:new Map()};
function project(lat,lng,z){const size=256*2**z,s=Math.sin(lat*Math.PI/180);return {x:(lng+180)/360*size,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*size}}
function unproject(x,y,z){const size=256*2**z;return {lng:x/size*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*y/size)))*180/Math.PI}}
function clusterPlaces(group,places){return places.filter(p=>p.areas.some(a=>group.areas.includes(a)))}
function selectCluster(id){selectedCluster=id;$('#area').value='';render();}
function mapSummary(){const group=TOKYO_GROUPS.find(g=>g.id===selectedCluster),all=visible(true);$('#map-title').textContent=selectedCluster==='multiple'?'Multiple locations':group?group.sub:'Where do you want to eat?';$('#map-hint').textContent=selectedCluster==='multiple'?'The sheet lists several branches for these places. Pick your branch in Google Maps.':group?group.hint:'Tap a cluster to see its food places. Drag to explore; use + / − to zoom.';$('#map-clear').hidden=!selectedCluster;$('#map-select').innerHTML='<button data-cluster="" class="'+(!selectedCluster?'selected':'')+'">All areas</button>'+TOKYO_GROUPS.map(g=>`<button data-cluster="${g.id}" class="${selectedCluster===g.id?'selected':''}">${g.name} <small>${clusterPlaces(g,visible(true)).length}</small></button>`).join('')+`<button data-cluster="multiple" class="${selectedCluster==='multiple'?'selected':''}">Multiple locations <small>${all.filter(p=>p.areas.includes('Multiple locations')).length}</small></button>`;if(view==='map')drawMap();}
function drawMap(){const el=$('#city-map');if(!el||view!=='map')return;const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;const c=project(mapState.lat,mapState.lng,mapState.zoom),left=c.x-w/2,top=c.y-h/2,visibleKeys=new Set();for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+h)/256);y++){if(y<0||y>=2**mapState.zoom)continue;const k=`${mapState.zoom}/${x}/${y}`;visibleKeys.add(k);let img=mapState.tiles.get(k);if(!img){img=document.createElement('img');img.alt='';img.draggable=false;img.src=`https://tile.openstreetmap.org/${k}.png`;img.onload=()=>{mapState.loaded=true;$('#map-error').hidden=true};img.onerror=()=>{if(!mapState.loaded)$('#map-error').hidden=false};$('#map-tiles').append(img);mapState.tiles.set(k,img)}img.style.transform=`translate(${x*256-left}px,${y*256-top}px)`}for(const [k,img]of mapState.tiles)if(!visibleKeys.has(k)){img.remove();mapState.tiles.delete(k)}$('#map-markers').innerHTML=TOKYO_GROUPS.map(g=>{const xy=project(g.lat,g.lng,mapState.zoom),n=clusterPlaces(g,visible(true)).length;if(!n)return '';return `<button data-cluster="${g.id}" class="map-marker ${selectedCluster===g.id?'selected':''}" style="left:${xy.x-left}px;top:${xy.y-top}px" aria-label="${g.sub}, ${n} food places"><strong>${n}</strong><span>${g.name}</span></button>`}).join('')}
function setupMap(){const el=$('#city-map');if(!el)return;let drag=null;el.addEventListener('pointerdown',e=>{if(e.target.closest('button,a'))return;drag={x:e.clientX,y:e.clientY,center:project(mapState.lat,mapState.lng,mapState.zoom)};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag)return;const c=unproject(drag.center.x-(e.clientX-drag.x),drag.center.y-(e.clientY-drag.y),mapState.zoom);mapState.lat=Math.max(35.3,Math.min(36,c.lat));mapState.lng=Math.max(139.3,Math.min(140,c.lng));drawMap()});const end=()=>drag=null;el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);$('#zoom-in').onclick=()=>{mapState.zoom=Math.min(14,mapState.zoom+1);drawMap()};$('#zoom-out').onclick=()=>{mapState.zoom=Math.max(10,mapState.zoom-1);drawMap()};$('#map-home').onclick=()=>{mapState.lat=35.697;mapState.lng=139.738;mapState.zoom=12;selectedCluster=null;render()};$('#map-clear').onclick=()=>selectCluster(null);document.addEventListener('click',e=>{const b=e.target.closest('[data-cluster]');if(b)selectCluster(b.dataset.cluster||null)});window.addEventListener('resize',()=>requestAnimationFrame(drawMap));}
